import * as functions from "firebase-functions";
import express from "express";
import cors from "cors";
import nationalParksRoute from "./routes/nationalParksRoute";
import parkReviews from "./routes/parkReviews";
import parkPosts from "./routes/parkPosts";
const app = express();
app.use(cors());
app.use(express.json());
app.use("/parkAccount", nationalParksRoute);
app.use("/parkReview", parkReviews);
app.use("/parkPosts", parkPosts);
export const api = functions.https.onRequest(app);
