import * as functions from "firebase-functions";
import express from "express";
import cors from "cors";
import NationalParksRoute from "./routes/NationalParksRoute";
import ParkReviews from "./routes/ParkReviews";
const app = express();
app.use(cors());
app.use(express.json());
app.use("/parkAccount", NationalParksRoute);
app.use("/parkReview", ParkReviews);
export const api = functions.https.onRequest(app);
