import * as functions from "firebase-functions";
import express from "express";
import cors from "cors";
import nationalParksRoute from "./routes/nationalParksRoute";
import parkReviewsRoute from "./routes/ParkReviewsRoute";
import parkPostsRoute from "./routes/parkPostsRoute";
const app = express();
app.use(cors());
app.use(express.json());
app.use("/parkAccount", nationalParksRoute);
app.use("/parkReview", parkReviewsRoute);
app.use("/parkPosts", parkPostsRoute);
export const api = functions.https.onRequest(app);
